#!/bin/bash
if [ $# -ne 3 ]
then
    echo "Usage: $0  ip  username  password"
    exit 2
fi
IP=$1
LOGIN=$2
PASS=$3
 

SESSION=`curl --silent -o /dev/null  "http://$IP/cgi/login.cgi"  -d "name=$LOGIN&pwd=$PASS"   --cookie-jar -|tail -1 |awk '{printf $7}'`
# checking the session id
if [ $? -ne 0 ]
then
    echo "* Could not fetch the session id, exiting"
    exit 1
fi
if [ "$SESSION" == "" ]
then
    echo "* Invalid credentials, exiting"
    exit 1
fi
 


cat >/var/www/html/Java/jviewer.jnlp << END



<jnlp spec="1.0+" codebase="https://$IP/">
  <information>
    <title>ATEN Java iKVM Viewer</title>
    <vendor>ATEN</vendor>
    <description>Java Web Start Application</description>
  </information>

  <security>
   <all-permissions/>
  </security>

  <resources>
    <property name="jnlp.packEnabled" value="true"/>
    <property name="jnlp.versionEnabled" value="true"/>
    <j2se version="1.6.0+" initial-heap-size="32M" max-heap-size="128M"/>
    <jar href="iKVM.jar" download="eager" main="true" version="1.69.17.0x0"/>
  </resources>

  <resources os="Windows" arch="x86">
    <nativelib href="libwin_x86.jar" download="eager" version="1.0.3"/>
  </resources>
  <resources os="Windows" arch="x86_64">
    <nativelib href="libwin_x86_64.jar" download="eager" version="1.0.3"/>
  </resources>
  <resources os="Windows" arch="amd64">
    <nativelib href="libwin_x86_64.jar" download="eager" version="1.0.3"/>
  </resources>

  <resources os="Linux" arch="i386">
    <nativelib href="liblinux_x86.jar" download="eager" version="1.0.3"/>
  </resources>
  <resources os="Linux" arch="x86">
    <nativelib href="liblinux_x86.jar" download="eager" version="1.0.3"/>
  </resources>
  <resources os="Linux" arch="x86_64">
    <nativelib href="liblinux_x86_64.jar" download="eager" version="1.0.3"/>
  </resources>
  <resources os="Linux" arch="amd64">
    <nativelib href="liblinux_x86_64.jar" download="eager" version="1.0.3"/>
  </resources>

  <resources os="Mac OS X" arch="x86_64">
    <nativelib href="libmac_x86_64.jar" download="eager" version="1.0.3"/>
  </resources>

  <application-desc main-class="tw.com.aten.ikvm.KVMMain">
    <argument>$IP</argument>
    <argument>$SESSION</argument>
    <argument>$SESSION</argument>
	<argument>null</argument>
    <argument>5900</argument>
    <argument>623</argument>
    <argument>2</argument>
    <argument>0</argument>
  </application-desc>
</jnlp>
END
